import '@/app/globals.css';
import ModalProvider from '@/components/ui/Modal/ModalProvider';

export const metadata = {
  title: 'Experia UI 테스트 페이지',
  description: 'Generated by Next.js',
};

export default function TestPageLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ko'>
      <body>
        {children}
        <ModalProvider />
      </body>
    </html>
  );
}
