import { SpeedInsights } from '@vercel/speed-insights/next';
import type { Metadata } from 'next';

import '@/app/globals.css';
import Footer from '@/components/layout/Footer';
import Header from '@/components/layout/Header';
import { Providers } from '@/components/provider/Providers';
import { pretendard } from '@/utils/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <link rel='icon' href='/favicon.ico' sizes='any' />
      <link rel='icon' href='/favicon-big.ico' type='image/png' sizes='400x400' />
      <body className={pretendard.className}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
        <SpeedInsights />
      </body>
    </html>
  );
}
