import '@/app/globals.css';
import { pretendard } from '@/utils/fonts';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={pretendard.className}>{children}</body>
    </html>
  );
}
